version: '3.8'

services:
  react_native_app:
    build:
      context: .  # Docker context is the current directory
      dockerfile: Dockerfile  # Dockerfile in the same directory
    environment:
      - NODE_ENV=development  # Set environment variable inside the container
    tty: true  # Allocate a pseudo-TTY for interactive processes
    ports:
      - "19000:19000"  # Expo app (QR code and dev tools)
      - "19001:19001"  # Metro Bundler (React Native Bundler)
      - "19002:19002"  # Expo DevTools (Web interface)
    volumes:
      - ./:/app  # Mount the entire project folder to /app in the container
      - node_modules:/app/node_modules  # Persist node_modules in a Docker volume
    working_dir: /app  # Set the working directory inside the container
    command: ["npx" , "expo", "start", "--tunnel"]  # Start Expo in tunnel mode
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19002"]  # Check if Expo DevTools is running
      interval: 30s
      retries: 3
      start_period: 10s  # Grace period before health checks begin

volumes:
  node_modules:  # Named volume for node_modules to avoid conflicts
